name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        env:
          NODE_ENV: production
          
      - name: Create deployment directory
        run: |
          # Create a clean directory for GitHub Pages
          rm -rf deploy
          mkdir deploy
          # Copy all build files to deploy directory
          cp -r ./build/* ./deploy/
          # Add .nojekyll to deploy directory  
          touch ./deploy/.nojekyll
          # Add 404.html for SPA routing
          cp ./deploy/index.html ./deploy/404.html
          # Ensure index.html is at the root level
          ls -la ./deploy/
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './deploy'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
